"""Inicializando banco de dados

Revision ID: aafd8f3c95bb
Revises: 
Create Date: 2024-07-26 13:15:14.680272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafd8f3c95bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas_desaparecidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('numero_bi', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nome_pai', sa.String(length=100), nullable=True),
    sa.Column('nome_mae', sa.String(length=100), nullable=True),
    sa.Column('data_desaparecimento', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('numero_bi', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('admin', 'funcionario', 'usuario', name='tipo_usuario'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deteccoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.Column('imagem_capturada', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Enum('Desaparecido', 'Encontrado', name='estado_deteccao'), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas_desaparecidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deteccao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['deteccao_id'], ['deteccoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('deteccoes')
    op.drop_table('usuarios')
    op.drop_table('pessoas_desaparecidas')
    # ### end Alembic commands ###
